PimIV_Web/Controllers/ContasController.cs
using System.Web.Mvc;
using Model;
using DAL;
using System;
using PimIV_Web.Models.ViewModels;
using PimIV_Web.Models;

namespace PimIV_Web.Controllers
{
    public class ContasController : Controller
    {
        ContaDAO cDAO = new ContaDAO();
        HospedeDAO hDAO = new HospedeDAO();
        // GET: Contas
        public ActionResult FazerLogin()
        {
            if(SessaoSite.Conta != null)
            {
                return RedirectToAction("AcessarConta");
            }
            switch (SessaoSite.Mensagem)
            {
                case 1:
                    ViewBag.ErroCadastro = "Hóspede já possui conta. Faça login.";
                    break;
                case 2:
                    ViewBag.ErroCadastro = "Ocorreu um erro no cadastro\nVerifique seus dados";
                    break;
                case 3:
                    ViewBag.LoginInvalido = "Dados de login inválidos";
                    break;
                case 4:
                    ViewBag.ErroCadastro = "Faça login ou crie uma conta\npara registrar sua reserva";
                    break;
                default:
                    break;
            }
            SessaoSite.Mensagem = 0;
            return View();
        }


        [HttpPost]
        public ActionResult ValidarHosp(string email, string senha)
        {
            Conta conta = cDAO.ValidarHospede(email, senha);
            if (conta != null)
            {
                SessaoSite.Conta = conta;
                SessaoSite.Conta.HospAssociado = conta.HospAssociado;
                if(SessaoSite.Reserva != null)
                {
                    return RedirectToAction("Confirmar","Reservas",
                        new {tipo = SessaoSite.Reserva.Quarto.Tipo.NomeTipo });
                }
                return RedirectToAction("AcessarConta");
            }
            else
            {
                SessaoSite.Mensagem = 3;
                return RedirectToAction("FazerLogin");
            }
        }

        [HttpPost]
        public ActionResult CadastrarHospede(string nome,string email,
            DateTime nasc, string sexo, string cpfPass, string senha)
        {
            Hospede hospede = new Hospede();
            Conta conta = new Conta();
            try
            {
                hospede.Nome = nome;
                hospede.DataNascimento = nasc;
                hospede.Sexo = sexo[0];
                hospede.Email = email;
                if ((cpfPass.Contains(".") || cpfPass.Contains("-")))
                {
                    hospede.setarCPF(cpfPass);
                }
                else
                {
                    hospede.Passaporte = cpfPass;
                }
            }
            catch(Exception)
            {
                SessaoSite.Mensagem = 2;
                return RedirectToAction("FazerLogin");
            }
            string buscar = hospede.CPF != "" ? hospede.CPF : hospede.Passaporte;
            if(cDAO.HospPossuiConta(buscar) > 0 || hDAO.EmailRegistrado(email))
            {
                SessaoSite.Mensagem = 1;
                return RedirectToAction("FazerLogin");
            }
            if (hospede.HospedeValido() == "")
            {
                hDAO.Inserir_Att(hospede);
            }
            else
            {
                SessaoSite.Mensagem = 2;
                return RedirectToAction("FazerLogin");
            }
            hospede = hDAO.Carregar(buscar);
            if(hospede == null)
            {
                SessaoSite.Mensagem = 2;
                return RedirectToAction("FazerLogin");
            }
            conta.HospAssociado = hospede;
            conta.Senha = senha;
            conta.NomeUsuario = " ";
            cDAO.Inserir_Att(conta);
            SessaoSite.Conta = conta;
            if (SessaoSite.Reserva != null)
            {
                return RedirectToAction("Confirmar", "Reservas",
                    new { tipo = SessaoSite.Reserva.Quarto.Tipo.NomeTipo });
            }
            return RedirectToAction("AcessarConta");
        }

        public ActionResult FazerLogoff()
        {
            SessaoSite.Conta = null;
            SessaoSite.Reserva = null;
            return RedirectToAction("FazerLogin");
        }

        public ActionResult AcessarConta()
        {
            switch (SessaoSite.Mensagem)
            {
                case 5:
                    ViewBag.MensagemHospede = "Dados atualizados!";
                    break;
                case 6:
                    ViewBag.MensagemHospede = "Reserva registrada com sucesso!";
                    break;
                default:
                    break;
            }
            SessaoSite.Mensagem = 0;
            HospedeViewModel mostrar = new HospedeViewModel();
            if(SessaoSite.Conta != null)
            {
                mostrar.Conta = SessaoSite.Conta;
                mostrar.Hospede = SessaoSite.Conta.HospAssociado;
                return View(mostrar);
            }
            else
            {
                return RedirectToAction("FazerLogin");
            }
        }

        public ActionResult Edit()
        {
            HospedeViewModel mostrar = new HospedeViewModel();
            if (SessaoSite.Conta != null)
            {
                mostrar.Conta = SessaoSite.Conta;
                mostrar.Hospede = SessaoSite.Conta.HospAssociado;
                return View(mostrar);
            }
            else
            {
                return RedirectToAction("FazerLogin");
            }
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            //collection: 1-6 = criar hospede/10-11 = criar conta
            Conta conta = new Conta();
            Hospede hospede = new Hospede();
            hospede.Nome = collection[1].ToString();
            hospede.DataNascimento = DateTime.Parse(collection[2].ToString());
            hospede.Sexo = char.Parse(collection[3].ToString());
            hospede.Email = collection[4].ToString();
            hospede.Telefone = collection[5].ToString();
            hospede.setarCPF(collection[6].ToString());
            hospede.Passaporte = collection[7].ToString();
            conta.NomeUsuario = collection[8].ToString();
            conta.Senha = collection[9].ToString();
            hDAO.Inserir_Att(hospede);
            string cpfPass = !hospede.CPF.Contains(" ")
                ? hospede.CPF : hospede.Passaporte;
            hospede = hDAO.Carregar(cpfPass);
            conta.HospAssociado = hospede;
            cDAO.Inserir_Att(conta);
            SessaoSite.Conta = conta;
            SessaoSite.Conta.HospAssociado = conta.HospAssociado;
            SessaoSite.Mensagem = 5;
            return RedirectToAction("AcessarConta");
        }
    }
}

PimIV_Web/Views/Contas/AcessarConta.cshtml
@model PimIV_Web.Models.ViewModels.HospedeViewModel

@{
    ViewBag.Title = "AcessarConta";
}
@Styles.Render("~/Content/css")

<div class="exibirDados">
    <h2>AcessarConta</h2>

    <span>@ViewBag.MensagemHospede</span>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hospede.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospede.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospede.DataNascimento.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospede.DataNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospede.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospede.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospede.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospede.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospede.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospede.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospede.CPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospede.CPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospede.Passaporte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospede.Passaporte)
        </dd>
        
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Conta.NomeUsuario)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Conta.NomeUsuario)
        </dd>
    </dl>

</div>
<p>
    @Html.ActionLink("Editar dados", "Edit") |
    @Html.ActionLink("Sair", "FazerLogoff")
</p>

<style>
    .exibirDados {
        margin-top: 12vh;
        margin-left: 185px;
    }
</style>

PimIV_Web/Views/Contas/Edit.cshtml
@model PimIV_Web.Models.ViewModels.HospedeViewModel

@{
    ViewBag.Title = "Edit";
}

@Styles.Render("~/Content/css")

<div class="editarDados">
    <h2>Edite seus dados:</h2>
    @using (Html.BeginForm("Edit", "Contas", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model.Hospede.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
    @Html.EditorFor(model => model.Hospede.Nome, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Hospede.Nome, "", new { @class = "text-danger" })
</div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hospede.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Hospede.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Hospede.DataNascimento, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hospede.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Hospede.Sexo, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Hospede.Sexo, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hospede.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Hospede.Email, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Hospede.Email, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hospede.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Hospede.Telefone, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Hospede.Telefone, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hospede.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Hospede.CPF, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Hospede.CPF, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hospede.Passaporte, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Hospede.Passaporte, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Hospede.Passaporte, "", new { @class = "text-danger" })
    </div>

    <div class="form-horizontal">
        <h2>Edite seus dados de login:</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Conta.NomeUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Conta.NomeUsuario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Conta.NomeUsuario, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Conta.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Conta.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Conta.Senha, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Cancelar edição", "AcessarConta")
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>
</div>
    }
</div>

<style>
    .editarDados {
        margin-top: 12vh;
        margin-left: 185px;
    }
</style>

PimIV_Web/Views/Contas/FazerLogin.cshtml
@model Model.Conta

@{
    ViewBag.Title = "FazerLogin";
    int dia = DateTime.Now.Day;
    int mes = DateTime.Now.Month;
    int ano = DateTime.Now.Year - 18;
    string NascMax = ano + "-" + mes + "-" + dia;
}

<script src="~/DesignPaginas/Scripts/FazerLogin.js"></script>
<link href="~/DesignPaginas/Style/FazerLogin.css" rel="stylesheet" />
<div class="containerLogin">

    
    <div class="content first-content">

        <div class="first-column">
            <h2 class="title title-primary"> Bem-vind@@!</h2><br>
            <p class="description description-primary"> Para garantir sua reserva</p>
            <p class="description description-primary">por favor, logue com seus dados pessoais</p><br>
            <p><span>@ViewBag.LoginInvalido</span></p>
            <p><span>@ViewBag.ErroCadastro</span></p>
            <button id="signin" class="btn btn-primary">Entrar</button>
        </div>

        <div class="second-column">
            <h2 class="title title-second"> Criar uma conta </h2>
            <p class="description description-second">Cadastre-se usando seus dados pessoais.</p>
            
        <form class="form" method="post" action="@Url.Action("CadastrarHospede","Contas")">

                <label class="label-input">
                    <i class="fas fa-user icon-modify"></i>
                    <input type="text" placeholder="Nome" name="nome" required>
                </label>
                <label class="label-input">
                    <i class="fas fa-calendar icon-modify"></i>
                    <input type="date" name="nasc" min="1910-01-01" 
                           max="@NascMax" required>
                </label>


                <label class="label-input">
                    <i class="fas fa-venus-mars icon-modify"></i>
                    <input type="text" placeholder="Gênero (F/M/Outro)" name="sexo" required>

                </label>

                <label class="label-input">
                    <i class="fas fa-address-card icon-modify"></i>
                    <input type="text" placeholder="CPF/Passaporte" name="cpfPass" required>
                </label>


                <label class="label-input ">
                    <i class="fas fa-envelope icon-modify"></i>
                    <input type="email" placeholder="Email" name="email" required>
                </label>

                <label class="label-input ">
                    <i class="fas fa-lock icon-modify"></i>
                    <input type="password" placeholder="Senha" name="senha" required>
                </label>

                <button class="btn btn-second">Cadastrar</button>

            </form>
        </div><!-- second column -->

    </div> <!--final first-content-->


    <div class="content second-content">
        <div class="first-column">
            <h2 class="title title-primary">Olá!</h2>
            <p class="description description-primary "> Cadastre-se com suas informações pessoais</p>
            <p class="description description-primary">e comece sua jornada conosco.</p>
            <button id="signup" class="btn btn-primary">Cadastre-se</button>
        </div>

        <div class="second-column">
            <h2 class="title title-second">Acessar conta </h2>
            <p class=" description description-second">Use os seus dados de acesso para entrar</p>
            <form method="post" action="@Url.Action("ValidarHosp","Contas")" class="form">
                <label class="label-input ">
                    <i class="fas fa-envelope icon-modify"></i>
                    <input type="email" name="email" placeholder="Email" required>
                </label>

                <label class="label-input ">
                    <i class="fas fa-lock icon-modify"></i>
                    <input type="password" name="senha" placeholder="Senha" required>
                </label>

                <button type="submit" class="btn btn-second">Entrar</button>


            </form>
        </div>

    </div> <!--final first-content-->
</div> <!--div do container-->
<!--</div>-->     <!--Second content-->

<script src="app.js"></script>


<script>
    var btnSingnin = document.querySelector("#signin");
    var btnSingnup = document.querySelector("#signup");


    var body = document.querySelector("body");

    btnSingnin.addEventListener("click", function () {
        body.className = "signin-js";
    });

    btnSingnup.addEventListener("click", function () {
        body.className = "signup-js";
    });
</script>   